# Generated by Django 3.2.18 on 2023-03-24 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230324_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sdtudents',
            new_name='students',
        ),
    ]
