# Generated by Django 4.1.4 on 2022-12-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_birth_date_alter_profile_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
