# Generated by Django 3.2.18 on 2023-03-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_sdtudents_profile_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='students',
        ),
        migrations.AddField(
            model_name='profile',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='_main_profile_students_+', to='main.Profile'),
        ),
    ]
