# Generated by Django 3.2.18 on 2023-03-24 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230324_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='students',
        ),
        migrations.AddField(
            model_name='profile',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.profile'),
        ),
    ]
