# Generated by Django 4.1.4 on 2023-01-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='priority',
        ),
    ]
