# Generated by Django 3.2.18 on 2023-03-24 11:31

from django.db import migrations, models
import sdu.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_students_profile_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture_url',
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=sdu.main.models.image_name),
        ),
    ]
