# Generated by Django 4.1.4 on 2023-01-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_projects_participants_remove_tasks_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_supervisor',
        ),
    ]
