# Generated by Django 4.1.4 on 2023-01-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_profile_is_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='teacher',
        ),
    ]
