# Generated by Django 4.1.4 on 2023-01-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_courses_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
