# Generated by Django 4.1.4 on 2023-01-03 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_profile_is_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.priorities'),
        ),
    ]
