# Generated by Django 4.1.4 on 2023-01-08 07:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_tasks_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameModel(
            old_name='Statuses',
            new_name='UserStatuses',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.taskstatuses'),
        ),
    ]
