# Generated by Django 4.1.4 on 2023-02-27 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0018_friendrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="profile_pics"),
        ),
        migrations.AddField(
            model_name="profile",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="course_of_study",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="profile",
            name="year_of_study",
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
