# Generated by Django 4.1.4 on 2023-03-09 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0019_profile_photo_profile_supervisor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="course_supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_supervisor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
